# Generated by Django 4.1 on 2022-10-26 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_article"),
    ]

    operations = [
        migrations.DeleteModel(name="Article",),
    ]
